// Static assets for the HX Client UI.
//
// Two sources, same shape — a map from URL path to a file path readable with
// Bun.file():
//
//   • embedded — `bun run build` runs scripts/gen-ui-assets.ts, which writes
//     src/ui-assets.gen.ts (gitignored) importing every ui/dist file
//     `with { type: "file" }`; `bun build --compile` embeds those into the
//     binary and the import yields /$bunfs/… paths at runtime.
//   • disk — running from a source checkout without the generated module
//     (plain `bun run dev`), serve ui/dist directly if it has been built.
//
// Lookups go through the map only — request paths are never joined onto the
// filesystem, so traversal is impossible by construction.

import { readdirSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

export interface UiAssets {
  mode: "embedded" | "disk";
  /** URL path ("/index.html", "/assets/index-abc.js") → Bun.file()-able path. */
  files: Record<string, string>;
}

const CONTENT_TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".ico": "image/x-icon",
  ".json": "application/json",
  ".map": "application/json",
  ".txt": "text/plain; charset=utf-8",
  ".woff2": "font/woff2",
  ".woff": "font/woff",
};

export function contentTypeFor(urlPath: string): string {
  const dot = urlPath.lastIndexOf(".");
  const ext = dot >= 0 ? urlPath.slice(dot).toLowerCase() : "";
  return CONTENT_TYPES[ext] ?? "application/octet-stream";
}

/** Recursively list files under a dist dir as URL-path → absolute-path. */
export function mapDistDir(distDir: string): Record<string, string> {
  const files: Record<string, string> = {};
  const stack = [distDir];
  while (stack.length > 0) {
    const dir = stack.pop() as string;
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- dir
    // descends from the compile-time ui/dist root, never from request input.
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const abs = join(dir, entry.name);
      if (entry.isDirectory()) {
        stack.push(abs);
      } else if (entry.isFile()) {
        const rel = abs.slice(distDir.length).replaceAll("\\", "/");
        files[rel.startsWith("/") ? rel : `/${rel}`] = abs;
      }
    }
  }
  return files;
}

/**
 * Resolve the UI assets, embedded first, disk fallback. Returns null when
 * neither exists (source checkout without a built ui/) — callers print the
 * remedy and exit.
 */
export async function loadUiAssets(): Promise<UiAssets | null> {
  try {
    // Generated by scripts/gen-ui-assets.ts; absent in a fresh checkout. The
    // literal specifier keeps the bundler embedding it when it exists at
    // compile time; the runtime catch covers dev checkouts where it doesn't.
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore -- src/ui-assets.gen.ts is generated at build time
    const gen = (await import("../ui-assets.gen.js")) as {
      UI_ASSETS: Record<string, string>;
    };
    if (Object.keys(gen.UI_ASSETS).length > 0) {
      return { mode: "embedded", files: gen.UI_ASSETS };
    }
  } catch {
    // fall through to disk mode
  }
  try {
    const distDir = fileURLToPath(new URL("../../ui/dist", import.meta.url));
    const files = mapDistDir(distDir);
    if (files["/index.html"]) return { mode: "disk", files };
  } catch {
    // no built ui on disk either
  }
  return null;
}
