// Generates src/ui-assets.gen.ts (gitignored) from ui/dist: one
// `with { type: "file" }` import per built file, so `bun build --compile`
// embeds the whole web UI into the single hx binary. Runs as part of
// `bun run build`, after the ui build; fails loudly when ui/dist is missing
// so a binary can never silently ship without its UI.

import { existsSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = fileURLToPath(new URL("..", import.meta.url));
const distDir = join(repoRoot, "ui", "dist");
const outFile = join(repoRoot, "src", "ui-assets.gen.ts");

if (!existsSync(join(distDir, "index.html"))) {
  console.error("gen-ui-assets: ui/dist/index.html not found — run `bun run build:ui` first.");
  process.exit(1);
}

const files: string[] = [];
const stack = [distDir];
while (stack.length > 0) {
  const dir = stack.pop() as string;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const abs = join(dir, entry.name);
    if (entry.isDirectory()) stack.push(abs);
    else if (entry.isFile()) files.push(abs);
  }
}
files.sort();

const lines: string[] = [
  "// AUTO-GENERATED by scripts/gen-ui-assets.ts — do not edit, do not commit.",
  "// Maps URL paths to embedded ui/dist files (see src/ui/assets.ts).",
  "// @ts-nocheck — tsc has no model for `with { type: \"file\" }` import",
  "// attributes (it sees HTMLBundle/any); at runtime each import is a path",
  "// string, embedded into the binary by `bun build --compile`.",
  "",
];
const entries: string[] = [];
files.forEach((abs, i) => {
  const rel = abs.slice(distDir.length).replaceAll("\\", "/");
  const urlPath = rel.startsWith("/") ? rel : `/${rel}`;
  lines.push(`import f${i} from "../ui/dist${urlPath}" with { type: "file" };`);
  entries.push(`  ${JSON.stringify(urlPath)}: f${i},`);
});
lines.push("", "export const UI_ASSETS: Record<string, string> = {", ...entries, "};", "");

writeFileSync(outFile, lines.join("\n"));
console.log(`gen-ui-assets: embedded ${files.length} files from ui/dist`);
